branches:
  only:
    - master

platform:
  - x86
  - x64

environment:
  matrix:
    - USE_SDL2: true
    - USE_SDL2: false

install:
  - git submodule update --init --recursive
  - set PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;%PATH
  - set MINGW_ARCH=i686
  - if [%PLATFORM%]==[x64] set MINGW_ARCH=x86_64
  - set MINGW_SDL=SDL
  - if [%USE_SDL2%]==[true] set MINGW_SDL=SDL2
  - pacman --noconfirm --needed -Sy
      pkg-config
      mingw-w64-%MINGW_ARCH%-toolchain
      mingw-w64-%MINGW_ARCH%-cmake
      mingw-w64-%MINGW_ARCH%-zlib
      mingw-w64-%MINGW_ARCH%-%MINGW_SDL%
      mingw-w64-%MINGW_ARCH%-%MINGW_SDL%_image
      mingw-w64-%MINGW_ARCH%-%MINGW_SDL%_mixer

build_script:
  - set MSYSTEM=MINGW32
  - if [%PLATFORM%]==[x64] set MSYSTEM=MINGW64
  - cmake --version
  - make --version
  - mkdir build
  - if [%USE_SDL2%]==[false] (
    bash -lc "
      cd $APPVEYOR_BUILD_FOLDER/build;
      cmake .. -G 'Unix Makefiles';
      make" )
  - if [%USE_SDL2%]==[true] (
    bash -lc "
      cd $APPVEYOR_BUILD_FOLDER/build;
      cmake .. -G 'Unix Makefiles' -DUSE_SDL2_LIBS=1;
      make smw" )

artifacts:
  - path: build\Binaries\Release\*.exe
