branches:
  only:
    - master

platform:
  - x86
  - x64

install:
  - git submodule update --init --recursive
  - echo Installing dependencies
  - choco install -y wget 7zip
  - set PATH="C:\Program Files\7-Zip";C:\MinGW\bin;%PATH%
  - wget --no-check-certificate https://www.libsdl.org/release/SDL-devel-1.2.15-mingw32.tar.gz
  - wget --no-check-certificate https://www.libsdl.org/projects/SDL_image/release/SDL_image-devel-1.2.12-VC.zip
  - wget --no-check-certificate https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-devel-1.2.12-VC.zip
  - 7z x SDL-devel-1.2.15-mingw32.tar.gz
  - 7z x -xr!._\* -xr!man -xr!docs SDL-devel-1.2.15-mingw32.tar
  - 7z x SDL_image-devel-1.2.12-VC.zip
  - 7z x SDL_mixer-devel-1.2.12-VC.zip
  - xcopy /S/Y SDL_image-1.2.12 SDL-1.2.15
  - xcopy /S/Y SDL_mixer-1.2.12 SDL-1.2.15
  - set SDLDIR=%CD%\SDL-1.2.15
  - echo SDLDIR set to %SDLDIR%

build_script:
  - C:\MinGW\msys\1.0\bin\sh --login -c "
      cd /c/projects/supermariowar;
      mkdir build;
      cd build;
      cmake --version;
      cmake .. -G 'MSYS Makefiles';
      cmake --build ."

artifacts:
  - path: supermariowar/build/Binaries/Release/*.exe
