language: cpp

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

env:
  - SMW_USE_SDL2=false
  - SMW_USE_SDL2=true

branches:
  only:
    - master

before_script:
  - $CXX --version
  - cmake --version
  - if [[ "$SMW_USE_SDL2" == "false" ]]; then sdl-config --version; fi
  - if [[ "$SMW_USE_SDL2" == "true" ]];  then sdl2-config --version; fi

script:
  - mkdir build && cd build
  - if [[ "$SMW_USE_SDL2" == "false" ]]; then cmake ..; fi
  - if [[ "$SMW_USE_SDL2" == "true" ]];  then cmake -D USE_SDL2_LIBS:BOOL=ON ..; fi
  - if [[ "$SMW_USE_SDL2" == "false" ]]; then make; else make smw; fi

addons:
  apt:
    packages:
    - cmake
    - gcc-4.8
    - g++-4.8
    - libsdl1.2-dev
    - libsdl-image1.2-dev
    - libsdl-mixer1.2-dev
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-mixer-dev
